/* 
 * API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Cars
    /// </summary>
    [DataContract]
    public partial class Cars :  IEquatable<Cars>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Cars" /> class.
        /// </summary>
        /// <param name="cars">cars.</param>
        public Cars(List<Car> cars = default(List<Car>))
        {
            this._Cars = cars;
        }
        
        /// <summary>
        /// Gets or Sets _Cars
        /// </summary>
        [DataMember(Name="cars", EmitDefaultValue=false)]
        public List<Car> _Cars { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Cars {\n");
            sb.Append("  _Cars: ").Append(_Cars).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Cars);
        }

        /// <summary>
        /// Returns true if Cars instances are equal
        /// </summary>
        /// <param name="input">Instance of Cars to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Cars input)
        {
            if (input == null)
                return false;

            return 
                (
                    this._Cars == input._Cars ||
                    this._Cars != null &&
                    this._Cars.SequenceEqual(input._Cars)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this._Cars != null)
                    hashCode = hashCode * 59 + this._Cars.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
