/* 
 * API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Laps
    /// </summary>
    [DataContract]
    public partial class Laps :  IEquatable<Laps>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Laps" /> class.
        /// </summary>
        /// <param name="laps">laps.</param>
        public Laps(List<Lap> laps = default(List<Lap>))
        {
            this._Laps = laps;
        }
        
        /// <summary>
        /// Gets or Sets _Laps
        /// </summary>
        [DataMember(Name="laps", EmitDefaultValue=false)]
        public List<Lap> _Laps { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Laps {\n");
            sb.Append("  _Laps: ").Append(_Laps).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Laps);
        }

        /// <summary>
        /// Returns true if Laps instances are equal
        /// </summary>
        /// <param name="input">Instance of Laps to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Laps input)
        {
            if (input == null)
                return false;

            return 
                (
                    this._Laps == input._Laps ||
                    this._Laps != null &&
                    this._Laps.SequenceEqual(input._Laps)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this._Laps != null)
                    hashCode = hashCode * 59 + this._Laps.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
