/* 
 * API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Car
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CarTests
    {
        // TODO uncomment below to declare an instance variable for Car
        //private Car instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Car
            //instance = new Car();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Car
        /// </summary>
        [Test]
        public void CarInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Car
            //Assert.IsInstanceOfType<Car> (instance, "variable 'instance' is a Car");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Marker1'
        /// </summary>
        [Test]
        public void Marker1Test()
        {
            // TODO unit test for the property 'Marker1'
        }
        /// <summary>
        /// Test the property 'Marker2'
        /// </summary>
        [Test]
        public void Marker2Test()
        {
            // TODO unit test for the property 'Marker2'
        }
        /// <summary>
        /// Test the property 'Marker3'
        /// </summary>
        [Test]
        public void Marker3Test()
        {
            // TODO unit test for the property 'Marker3'
        }
        /// <summary>
        /// Test the property 'Marker4'
        /// </summary>
        [Test]
        public void Marker4Test()
        {
            // TODO unit test for the property 'Marker4'
        }
        /// <summary>
        /// Test the property 'DriverId'
        /// </summary>
        [Test]
        public void DriverIdTest()
        {
            // TODO unit test for the property 'DriverId'
        }
        /// <summary>
        /// Test the property 'TeamId'
        /// </summary>
        [Test]
        public void TeamIdTest()
        {
            // TODO unit test for the property 'TeamId'
        }
        /// <summary>
        /// Test the property 'CategoryId'
        /// </summary>
        [Test]
        public void CategoryIdTest()
        {
            // TODO unit test for the property 'CategoryId'
        }

    }

}
