/* 
 * API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Drivers
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DriversTests
    {
        // TODO uncomment below to declare an instance variable for Drivers
        //private Drivers instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Drivers
            //instance = new Drivers();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Drivers
        /// </summary>
        [Test]
        public void DriversInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Drivers
            //Assert.IsInstanceOfType<Drivers> (instance, "variable 'instance' is a Drivers");
        }


        /// <summary>
        /// Test the property '_Drivers'
        /// </summary>
        [Test]
        public void _DriversTest()
        {
            // TODO unit test for the property '_Drivers'
        }

    }

}
