/* 
 * API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Laps
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class LapsTests
    {
        // TODO uncomment below to declare an instance variable for Laps
        //private Laps instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Laps
            //instance = new Laps();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Laps
        /// </summary>
        [Test]
        public void LapsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Laps
            //Assert.IsInstanceOfType<Laps> (instance, "variable 'instance' is a Laps");
        }


        /// <summary>
        /// Test the property '_Laps'
        /// </summary>
        [Test]
        public void _LapsTest()
        {
            // TODO unit test for the property '_Laps'
        }

    }

}
