/* 
 * API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Race
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class RaceTests
    {
        // TODO uncomment below to declare an instance variable for Race
        //private Race instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Race
            //instance = new Race();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Race
        /// </summary>
        [Test]
        public void RaceInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Race
            //Assert.IsInstanceOfType<Race> (instance, "variable 'instance' is a Race");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Track'
        /// </summary>
        [Test]
        public void TrackTest()
        {
            // TODO unit test for the property 'Track'
        }
        /// <summary>
        /// Test the property 'EventId'
        /// </summary>
        [Test]
        public void EventIdTest()
        {
            // TODO unit test for the property 'EventId'
        }

    }

}
