/* 
 * API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Races
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class RacesTests
    {
        // TODO uncomment below to declare an instance variable for Races
        //private Races instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Races
            //instance = new Races();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Races
        /// </summary>
        [Test]
        public void RacesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Races
            //Assert.IsInstanceOfType<Races> (instance, "variable 'instance' is a Races");
        }


        /// <summary>
        /// Test the property '_Races'
        /// </summary>
        [Test]
        public void _RacesTest()
        {
            // TODO unit test for the property '_Races'
        }

    }

}
