/* 
 * API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Teams
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TeamsTests
    {
        // TODO uncomment below to declare an instance variable for Teams
        //private Teams instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Teams
            //instance = new Teams();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Teams
        /// </summary>
        [Test]
        public void TeamsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Teams
            //Assert.IsInstanceOfType<Teams> (instance, "variable 'instance' is a Teams");
        }


        /// <summary>
        /// Test the property '_Teams'
        /// </summary>
        [Test]
        public void _TeamsTest()
        {
            // TODO unit test for the property '_Teams'
        }

    }

}
